### ISSUE TITLE
Possibility to put libcoro into a mainloop?

### ISSUE THREAD

**Issue by niansa** [jbaldwin/libcoro#103] opened 2021-07-28 10:47 UTC
I'd just like to write a libcoro wrapper around some boost::asio stuff, however I couldn't figure out how to use sync_wait into a mainloop like that one of boost asio? Any idea?

**Comment by jbaldwin** [comment] 2021-07-28 17:49
I think you'll want to use `coro::io_scheduler` and use the manual drive functions

```C++
/**
     * Given a thread_strategy_t::manual this function should be called at regular intervals to
     * process events that are ready.  If a using thread_strategy_t::spawn this is run continously
     * on a dedicated background thread and does not need to be manually invoked.
     * @param timeout If no events are ready how long should the function wait for events to be ready?
     *                Passing zero (default) for the timeout will check for any events that are
     *                ready now, and then return.  This could be zero events.  Passing -1 means block
     *                indefinitely until an event happens.
     * @param return The number of tasks currently executing or waiting to execute.
     */
    auto process_events(std::chrono::milliseconds timeout = std::chrono::milliseconds{0}) -> std::size_t;
```

It won't be possible to integrate `coro::sync_wait` into an event loop since its blocking.

**Comment by niansa** [comment] 2021-08-06 07:28
Nope, I can't use io_scheduler here, since it conflicts with some boost stuff.

**Comment by jbaldwin** [comment] 2021-08-07 15:22
Define "conflicts"?

**Comment by jbaldwin** [comment] 2021-10-21 16:55
Closing since I'm not sure what the problem is

**Closed by jbaldwin** 2021-10-21 16:55 UTC
